{% set name = "pyratlib" %}
{% set version = "0.7.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyratlib/{{ name }}-{{ version }}.tar.gz
  sha256: a6c11a7640e5e5f0012bee584f89d6d1cd21c35e53d161c5727f26166970aaf5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python-neo
    - matplotlib-base
    - numpy
    - pandas
    - python >=3.7
    - scikit-learn

test:
  imports:
    - pyratlib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyratlib/pyrat
  summary: PyRat is a user friendly library in python to analyze data from the DeepLabCut. Developed to help researchers unfamiliar with programming can perform animal behavior analysis more simpler.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pyratlib
    - tuliofalmeida
    - abnr
